name: equine-microbiome
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - anyio=4.10.0
  - aom=3.6.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - biopython=1.79
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.0.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - flask=3.1.2
  - fontconfig=2.14.1
  - fonttools=4.33.3
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.18.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.2
  - lark=1.2.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=20.1.8
  - libcups=2.4.2
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libllvm20=20.1.8
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxkbfile=1.1.0
  - libxml2=2.13.8
  - libxslt=1.1.41
  - lmdb=0.9.29
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - mistune=3.1.3
  - munkres=1.1.4
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nomkl=3.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.29
  - openblas-devel=0.3.29
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openpyxl=3.0.9
  - openssl=3.0.17
  - overrides=7.7.0
  - packaging=25.0
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=5.9.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.2
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2025.2
  - pyyaml=6.0
  - pyzmq=26.2.0
  - qtbase=6.9.1
  - qtdeclarative=6.9.1
  - qtshadertools=6.9.1
  - qtsvg=6.9.1
  - qttools=6.9.1
  - qtwebchannel=6.9.1
  - qtwebengine=6.9.1
  - qtwebsockets=6.9.1
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.22.3
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.13.2
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250809
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=14.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.31
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - cssselect2==0.8.0
      - pydyf==0.11.0
      - pyphen==0.17.2
      - reportlab==4.4.3
      - tinyhtml5==2.0.0
      - weasyprint==66.0
      - zopfli==0.2.3.post1
prefix: /home/trent/miniconda3/envs/equine-microbiome
